name: Basic CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
	CUSTOM_ENV: "my-custom-env"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run application check script
        run: ./app/check_app.sh

      - name: Display index.html content
        run: cat ./app/index.html

      - name: Display secrets and env vars
        env:
          FAKE_API_TOKEN: ${{ secrets.FAKE_API_TOKEN }}
          ENV_TYPE: ${{ secrets.ENV_TYPE }}
        run: |
          echo "FAKE_API_TOKEN=${FAKE_API_TOKEN}"
          echo "ENV_TYPE=${ENV_TYPE}"
          echo "CUSTOM_ENV=${CUSTOM_ENV}"
          echo "RUNNER_OS=${RUNNER_OS}"
